[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m backend.main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = 8008
